sudo: false

os:
  - linux
  - osx

language: node_js
node_js: "stable"

matrix:
  include:
    - os: osx
      osx_image: xcode11
      env:
        - TRAVIS_BUILD_OS=osx
    - os: linux
      dist: trusty
      services: docker
      language: generic
      env:
        - TRAVIS_BUILD_OS=linux

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

stages:
  - name: Test
    if: os = linux
  - name: lighthouse-keeper
    if: os = linux
  - name: Deploy Windows & Linux
    if: os = linux AND type != pull_request AND branch = master
  - name: Deploy Mac
    if: os = osx AND type != pull_request AND branch = master

jobs:
  include:
    - stage: Test
      script:
        - npm test
    - stage: lighthouse-keeper
      script:
        - npm run build
        - npx codechecks
    - stage: Deploy Mac
      script:
        - npm run release -- --mac
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy Linux
      script:
        - |
          if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            docker run --rm \
              --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
              -v ${PWD}:/project \
              -v ~/.cache/electron:/root/.cache/electron \
              -v ~/.cache/electron-builder:/root/.cache/electron-builder \
              electronuserland/builder:wine \
              /bin/bash -c "yarn --link-duplicates --pure-lockfile && npm run release -- --linux --win -c.snap.publish=github"
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine