sudo: false

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

stages:
  - name: Test

jobs:
  include:
    - stage: Test
      script:
        - npm test
