name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Installs Deps
      run: npm install
    - name: Runs Tests
      run: npm test
    - name: Runs a LightHouse-Keeper Analysis
      run: |
        npm run build
        travis_retry npx codechecks
