name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Deps
      run: npm ci
    - name: Runs Tests
      run: npm test
      env:
        CI: true
    - name: Runs a Lighthouse-Keeper Analysis
      run: |
        npm run build
        npx codechecks
      env: 
      CC_SECRET: ${{ secrets.CC_SECRET }}
